cluster: "PBS-Torque-Profile/pbs-submit.py --depend \"{dependencies}\""
cluster-status: "PBS-Torque-Profile/pbs-status.py"
jobscript: "PBS-Torque-Profile/pbs-jobscript.sh"
jobs: 8
immediate-submit: False
verbose: true
notemp: true
